#simple = (p*t*r)/100
#compound = p*(1+(r/100))**(n*t)
p = int(input())
t = int(input())
r = int(input())
n = int(input())
simple = (p*t*r)/100
print("simple interest is",simple)
compound = p*(1+(r/100))**(n*t)
print("compound interest is",compound)
